name: Run main sync script

on:
  # workflow_dispatch:
  schedule:
  - cron: "31 */2 * * *" # run every two hours

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.GH_WRITE_TOKEN}}

    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install node dependencies
      run: npm i

    - name: Run main sync script
      run: npm run start
      env:
        LANDLINE_NUMBER: ${{secrets.LANDLINE_NUMBER}}
        HASHED_PASSWORD: ${{secrets.HASHED_PASSWORD}}
        TIMEZONE: ${{secrets.TIMEZONE}}

    - name: Update git configs
      run: git config --global user.email "quota_observer@Raamyy.com" && git config --global user.name "Quota Observer"

    - name: Add changed files to repo
      run: git add -A

    - name: Commit files to repo
      run: git commit -m "update logs"
    
    - name: 🚀 push files to repo
      run: git push
